import prisma from "./src/lib/prisma.js";

async function testAbsent() {
  console.log('🔄 Running test auto absent check...');
  try {
    const today = new Date();
    // Simulate it's a working day to force absent (if today is Sunday it will insert holiday)
    
    const todayStart = new Date(today);
    todayStart.setHours(0, 0, 0, 0);
    
    const todayEnd = new Date(today);
    todayEnd.setHours(23, 59, 59, 999);

    const activeEmployees = await prisma.user.findMany({
      where: {
        role: { notIn: ['superadmin'] },
        status: 'active'
      }
    });

    let insertedCount = 0;
    const isSunday = today.getDay() === 0;

    for (const emp of activeEmployees) {
      if (!emp.organizationId) continue;

      const holiday = await prisma.holiday.findFirst({
        where: {
          organizationId: emp.organizationId,
          date: { gte: todayStart, lte: todayEnd }
        }
      });
      
      const isHolidayOrSunday = isSunday || !!holiday;

      if (isHolidayOrSunday) continue;

      const existingRecord = await prisma.attendance.findFirst({
        where: {
          employeeId: emp.id,
          date: { gte: todayStart, lte: todayEnd }
        }
      });

      if (!existingRecord) {
        await prisma.attendance.create({
          data: {
            employeeId: emp.id,
            organizationId: emp.organizationId,
            date: todayStart,
            status: 'absent',
            isLate: false,
            lateMinutes: 0,
            workingHours: 0,
            notes: 'Auto-generated by system (no punch-in)'
          }
        });
        insertedCount++;
      }
    }
    
    console.log(`✅ Auto-generated ${insertedCount} absent records`);
  } catch (error) {
    console.error('❌ Auto absent cron error:', error);
  } finally {
    await prisma.$disconnect();
  }
}

testAbsent();
