import cron from 'node-cron';
import prisma from '../lib/prisma.js';
import { startEscalationCron } from './escalationService.js';

export const startAllCronJobs = () => {
  startInviteExpiryCron();
  startEscalationCron();
  startAutoPunchOutCron();
  startAutoAbsentCron();
  startLeaveAllocationCron();
  console.log('✅ All cron jobs started');
};

const startInviteExpiryCron = () => {
  cron.schedule('0 1 * * *', async () => {
    console.log('🔄 Running invite token expiry check...');
    try {
      const result = await prisma.studyCenterInvite.updateMany({
        where: {
          status: 'pending',
          expiresAt: { lt: new Date() }
        },
        data: { status: 'expired' }
      });
      console.log(`✅ Expired ${result.count} invite tokens`);
    } catch (error) {
      console.error('❌ Invite expiry cron error:', error);
    }
  });
};

const startAutoPunchOutCron = () => {
  // Run at 12:01 AM every day
  cron.schedule('1 0 * * *', async () => {
    console.log('🔄 Running auto punch-out for unclosed attendances...');
    try {
      const todayStart = new Date();
      todayStart.setHours(0, 0, 0, 0);

      const pendingAttendances = await prisma.attendance.findMany({
        where: {
          checkOut: null,
          date: { lt: todayStart }
        }
      });

      let updatedCount = 0;
      for (const record of pendingAttendances) {
        if (!record.checkIn) continue;

        const checkOutTime = new Date(record.date);
        checkOutTime.setHours(23, 59, 59, 999);

        const checkInTime = new Date(record.checkIn).getTime();
        const workingHours = Number(((checkOutTime.getTime() - checkInTime) / 3600000).toFixed(2));

        const existingNotes = record.notes ? record.notes + '\n' : '';

        await prisma.attendance.update({
          where: { id: record.id },
          data: {
            checkOut: checkOutTime,
            workingHours,
            notes: existingNotes + 'Auto-punched out by system at midnight.'
          }
        });
        updatedCount++;
      }
      
      console.log(`✅ Auto-punched out ${updatedCount} employees`);
    } catch (error) {
      console.error('❌ Auto punch-out cron error:', error);
    }
  });
};

const startAutoAbsentCron = () => {
  // Run at 11:58 PM every day
  cron.schedule('58 23 * * *', async () => {
    console.log('🔄 Running auto absent check for missing attendances...');
    try {
      const today = new Date();
      const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
      const todayName = days[today.getDay()];
      
      const todayStart = new Date(today);
      todayStart.setHours(0, 0, 0, 0);
      
      const todayEnd = new Date(today);
      todayEnd.setHours(23, 59, 59, 999);

      const activeEmployees = await prisma.user.findMany({
        where: {
          role: { notIn: ['superadmin'] },
          status: 'active',
          requiresAttendance: true
        }
      });

      let insertedCount = 0;
      const orgSettingsCache: Record<string, any> = {};

      for (const emp of activeEmployees) {
        if (!emp.organizationId) continue;

        // Cache settings per organization
        if (!orgSettingsCache[emp.organizationId]) {
          const settings = await prisma.hRSettings.findUnique({
            where: { organizationId: emp.organizationId }
          });
          let workingDays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
          if (settings && settings.officeHours) {
            const officeHours = settings.officeHours as any;
            if (officeHours.workingDays && Array.isArray(officeHours.workingDays)) {
              workingDays = officeHours.workingDays;
            }
          }
          orgSettingsCache[emp.organizationId] = { workingDays };
        }

        const orgSettings = orgSettingsCache[emp.organizationId];
        const isWorkingDay = orgSettings.workingDays.includes(todayName);

        // Check if today is a Holiday in the database
        const holiday = await prisma.holiday.findFirst({
          where: {
            organizationId: emp.organizationId,
            date: { gte: todayStart, lte: todayEnd }
          }
        });

        // Only generate absent records on normal working days
        if (!isWorkingDay || !!holiday) {
           continue; 
        }

        const existingRecord = await prisma.attendance.findFirst({
          where: {
            employeeId: emp.id,
            date: { gte: todayStart, lte: todayEnd }
          }
        });

        if (!existingRecord) {
          await prisma.attendance.create({
            data: {
              employeeId: emp.id,
              organizationId: emp.organizationId,
              date: todayStart,
              status: 'absent',
              isLate: false,
              lateMinutes: 0,
              workingHours: 0,
              notes: 'Auto-generated by system (no punch-in)'
            }
          });
          insertedCount++;
        }
      }
      
      console.log(`✅ Auto-generated ${insertedCount} absent records`);
    } catch (error) {
      console.error('❌ Auto absent cron error:', error);
    }
  });
};



const startLeaveAllocationCron = () => {
  // Run at 00:01 on the 1st of every month to rollover leaves to the new month
  cron.schedule('1 0 1 * *', async () => {
    console.log('🔄 Running monthly leave allocation rollover cron...');
    try {
      const today = new Date();
      const currentMonth = today.getMonth() + 1; // 1-12
      const currentYear = today.getFullYear();

      // Determine previous month/year
      let prevMonth = currentMonth - 1;
      let prevYear = currentYear;
      if (prevMonth === 0) {
        prevMonth = 12;
        prevYear = currentYear - 1;
      }

      const activeEmployees = await prisma.user.findMany({
        where: {
          role: { notIn: ['superadmin'] },
          status: 'active'
        },
        include: { employeeProfileDetail: true }
      });

      let allocatedCount = 0;

      for (const emp of activeEmployees) {
        if (!emp.organizationId || !emp.employeeProfileDetail?.joinDate) continue;

        const joinDate = new Date(emp.employeeProfileDetail.joinDate);
        if (joinDate >= today) {
          continue; // Future join date, skip
        }

        // Check if allocation already exists for the CURRENT month
        const currentAllocation = await prisma.leaveAllocation.findUnique({
          where: {
            userId_year_month: {
              userId: emp.id,
              year: currentYear,
              month: currentMonth
            }
          }
        });

        if (currentAllocation) {
          // HR might have already set it in advance, don't overwrite
          continue;
        }

        // Find PREVIOUS month's allocation
        const prevAllocation = await prisma.leaveAllocation.findUnique({
          where: {
            userId_year_month: {
              userId: emp.id,
              year: prevYear,
              month: prevMonth
            }
          }
        });

        // Determine defaults if no previous month found (e.g., new employee)
        let sickLeave = 0;
        let casualLeave = 0;
        let earnedLeave = 0;
        let complementaryLeave = 0;

        if (prevAllocation) {
          // Rollover from previous month
          sickLeave = prevAllocation.sickLeave;
          casualLeave = prevAllocation.casualLeave;
          earnedLeave = prevAllocation.earnedLeave;
          complementaryLeave = prevAllocation.complementaryLeave;
        } else {
          // Leave defaults as 0. HR will manually allocate leaves when employee joins.
        }

        await prisma.leaveAllocation.create({
          data: {
            userId: emp.id,
            organizationId: emp.organizationId,
            year: currentYear,
            month: currentMonth,
            sickLeave,
            casualLeave,
            earnedLeave,
            complementaryLeave
          }
        });
        
        allocatedCount++;
      }
      
      console.log(`✅ Rolled over monthly leaves for ${allocatedCount} employees`);
    } catch (error) {
      console.error('❌ Monthly leave allocation rollover error:', error);
    }
  });
};
